import { StyledTokens } from "../../src/types";

const style = {
  fontSize: 20,
  fill: "#cccccc",
  wordWrapWidth: 500,
  wordWrap: true,
  breakLines: true,
  fontFamily: "monospace",
};
export const nobreakStyle = { breakLines: false, color: "#ff8888" };
const nestedStyle = {
  breakLines: true,
  color: "#8888ff",
};

export const styledTokens = {
  children: [
    "Really",
    " ",
    "long",
    " ",
    "normal",
    " ",
    "text",
    " ",
    "that",
    " ",
    "breaks",
    " ",
    "to",
    " ",
    "the",
    " ",
    "next",
    " ",
    "line.",
    "\n",
    "Normal",
    " ",
    "text",
    " ",
    "+",
    " ",
    {
      children: ["Text", " ", "that", " ", "doesn't", " ", "break."],
      style: nobreakStyle,
      tags: "nobreak",
    },
    "\n",
    "Longer",
    " ",
    "normal",
    " ",
    "text",
    " ",
    "+",
    " ",
    {
      children: [
        "Text",
        " ",
        "that",
        " ",
        "doesn't",
        " ",
        "break",
        " ",
        "(wraps",
        " ",
        "line)",
      ],
      style: nobreakStyle,
      tags: "nobreak",
    },
    "\n",
    {
      children: [
        "Really",
        " ",
        "long",
        " ",
        "text",
        " ",
        "that",
        " ",
        "doesn't",
        " ",
        "break",
        " ",
        "but",
        " ",
        "is",
        " ",
        "too",
        " ",
        "long",
        " ",
        "for",
        " ",
        "the",
        " ",
        "line?",
      ],
      style: nobreakStyle,
      tags: "nobreak",
    },
    "\n",
    {
      children: [
        "Nobreak",
        " ",
        "text",
        " ",
        "that",
        " ",
        "has",
        "\n",
        "an",
        " ",
        "explicit",
        " ",
        "line",
        " ",
        "break",
        " ",
        "in",
        " ",
        "the",
        " ",
        "middle.",
      ],
      style: nobreakStyle,
      tags: "nobreak",
    },
    "\n",
    {
      children: [
        "Long",
        " ",
        "Nobreak",
        " ",
        "text",
        " ",
        "that",
        " ",
        "extends",
        " ",
        "too",
        " ",
        "far",
        " ",
        "with",
        " ",
        {
          children: [
            "a",
            " ",
            "nested",
            " ",
            "breaking",
            " ",
            "text",
            " ",
            "tag",
          ],
          style: nestedStyle,
          tags: "nested",
        },
        " ",
        "in",
        " ",
        "the",
        " ",
        "middle.",
      ],
      style: nobreakStyle,
      tags: "nobreak",
    },
  ],
  style,
  tags: "",
} as StyledTokens;
